In [3]:
import numpy as np
matrix = np.matrix([[0.9,0.075,0.025],[0.15,0.8,0.05],[0.25,0.25,0.5]], dtype=float)
vector1 = np.matrix([[0.3,0.4,0.3]], dtype=float)
for i in range(100):
    vector1 = vector1*matrix
    print( "Current round:" , i+1)
    print( vector1)

Current round: 1
[[0.405  0.4175 0.1775]]
Current round: 2
[[0.4715  0.40875 0.11975]]
Current round: 3
[[0.5156 0.3923 0.0921]]
Current round: 4
[[0.54591  0.375535 0.078555]]
Current round: 5
[[0.567288 0.36101  0.071702]]
Current round: 6
[[0.5826362 0.3492801 0.0680837]]
Current round: 7
[[0.59378552 0.34014272 0.06607176]]
Current round: 8
[[0.60194632 0.33316603 0.06488765]]
Current round: 9
[[0.6079485  0.32790071 0.06415079]]
Current round: 10
[[0.61237646 0.3239544  0.06366914]]
Current round: 11
[[0.61564926 0.32100904 0.0633417 ]]
Current round: 12
[[0.61807111 0.31881635 0.06311253]]
Current round: 13
[[0.61986459 0.31718655 0.06294886]]
Current round: 14
[[0.62119333 0.3159763  0.06283037]]
Current round: 15
[[0.62217803 0.31507813 0.06274383]]
Current round: 16
[[0.62290791 0.31441182 0.06268027]]
Current round: 17
[[0.62344896 0.31391762 0.06263343]]
Current round: 18
[[0.62385006 0.31355112 0.06259882]]
Current round: 19
[[0.62414743 0.31327936 0.06257322]]
Current roun

In [4]:
import numpy as np
matrix = np.matrix([[0.8,0.175,0.025],[0.15,0.8,0.05],[0.25,0.25,0.5]], dtype=float)
vector1 = np.matrix([[0.3,0.4,0.3]], dtype=float)
for i in range(100):
    vector1 = vector1*matrix
    print( "Current round:" , i+1)
    print( vector1)

Current round: 1
[[0.375  0.4475 0.1775]]
Current round: 2
[[0.4115 0.468  0.1205]]
Current round: 3
[[0.429525  0.4765375 0.0939375]]
Current round: 4
[[0.438585   0.47988125 0.08153375]]
Current round: 5
[[0.44323363 0.48104081 0.07572556]]
Current round: 6
[[0.44567441 0.48132993 0.07299566]]
Current round: 7
[[0.44698793 0.48130588 0.07170619]]
Current round: 8
[[0.44771278 0.48119414 0.07109309]]
Current round: 9
[[0.44812261 0.48107832 0.07079907]]
Current round: 10
[[0.44835961 0.48098388 0.07065652]]
Current round: 11
[[0.4484994  0.48091416 0.07058644]]
Current round: 12
[[0.44858325 0.48086533 0.07055141]]
Current round: 13
[[0.44863425 0.48083219 0.07053356]]
Current round: 14
[[0.44866562 0.48081014 0.07052424]]
Current round: 15
[[0.44868508 0.48079565 0.07051927]]
Current round: 16
[[0.44869723 0.48078623 0.07051654]]
Current round: 17
[[0.44870485 0.48078013 0.07051501]]
Current round: 18
[[0.44870966 0.48077621 0.07051414]]
Current round: 19
[[0.44871269 0.48077369 0.07