In [13]:
import pandas as pd
from sklearn.base import BaseEstimator,TransformerMixin
import numpy as np

In [14]:
housing = pd.read_csv('housing.csv')

In [15]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [18]:
import numpy as np
def split_train_test(data, test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]

    return data.iloc[train_indices],data.iloc[test_indices]

In [19]:
train_set,test_set=split_train_test(housing,0.2)
print(len(train_set),"train+",len(test_set),"test") 

[ 2208  9969 14332 ...  3540  7220 11215]
16512 train+ 4128 test


In [10]:
rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6
class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [11]:
housing_extra_attribs

array([[-122.23, 37.88, 41.0, ..., 'NEAR BAY', 6.984126984126984,
        2.5555555555555554],
       [-122.22, 37.86, 21.0, ..., 'NEAR BAY', 6.238137082601054,
        2.109841827768014],
       [-122.24, 37.85, 52.0, ..., 'NEAR BAY', 8.288135593220339,
        2.8022598870056497],
       ...,
       [-121.22, 39.43, 17.0, ..., 'INLAND', 5.20554272517321,
        2.325635103926097],
       [-121.32, 39.43, 18.0, ..., 'INLAND', 5.329512893982808,
        2.1232091690544412],
       [-121.24, 39.37, 16.0, ..., 'INLAND', 5.254716981132075,
        2.616981132075472]], dtype=object)

In [26]:
housing = pd.read_csv('housing.csv')

In [32]:
import hashlib
def test_set_check(identifier, test_ratio, hash):
    return hash(np.int64(identifier)).digest()[-1] < 256 * test_ratio

def split_train_test_by_id(data, test_ratio, id_column, hash=hashlib.md5):
    ids = data[id_column]

    in_test_set = ids.apply(lambda id_: test_set_check(id_, test_ratio, hash))
    return data.loc[~in_test_set], data.loc[in_test_set]

In [30]:
housing_with_id = housing.reset_index() # adds an `index` column
train_set, test_set = split_train_test_by_id(housing_with_id, 0.2, "index")
train_set

index  longitude  latitude  housing_median_age  total_rooms  \
0          0    -122.23     37.88                41.0        880.0   
1          1    -122.22     37.86                21.0       7099.0   
2          2    -122.24     37.85                52.0       1467.0   
3          3    -122.25     37.85                52.0       1274.0   
6          6    -122.25     37.84                52.0       2535.0   
7          7    -122.25     37.84                52.0       3104.0   
8          8    -122.26     37.84                42.0       2555.0   
9          9    -122.25     37.84                52.0       3549.0   
10        10    -122.26     37.85                52.0       2202.0   
12        12    -122.26     37.85                52.0       2491.0   
13        13    -122.26     37.84                52.0        696.0   
14        14    -122.26     37.85                52.0       2643.0   
15        15    -122.26     37.85                50.0       1120.0   
16        16    -122.27     37.85                52.0       1966.0   
17        17    -122.27     37.85                52.0       1228.0   
18        18    -122.26     37.84                50.0       2239.0   
19        19    -122.27     37.84                52.0       1503.0   
21        21    -122.27     37.85                42.0       1639.0   
22        22    -122.27     37.84                52.0       2436.0   
24        24    -122.27     37.84                52.0       2224.0   
25        25    -122.28     37.85                41.0        535.0   
26        26    -122.28     37.85                49.0       1130.0   
27        27    -122.28     37.85                52.0       1898.0   
28        28    -122.28     37.84                50.0       2082.0   
29        29    -122.28     37.84                52.0        729.0   
30        30    -122.28     37.84                49.0       1916.0   
31        31    -122.28     37.84                52.0       2153.0   
32        32    -122.27     37.84                48.0       1922.0   
33        33    -122.27     37.83                49.0       1655.0   
36        36    -122.27     37.83                48.0       1798.0   
...      ...        ...       ...                 ...          ...   
20597  20597    -121.58     39.16                33.0       1897.0   
20599  20599    -121.56     39.16                35.0       2157.0   
20601  20601    -121.57     39.13                30.0        442.0   
20602  20602    -121.56     39.13                17.0       2277.0   
20603  20603    -121.54     39.13                18.0       4289.0   
20604  20604    -121.54     39.12                17.0       4251.0   
20605  20605    -121.58     39.12                26.0       2796.0   
20610  20610    -121.56     39.10                28.0       2130.0   
20612  20612    -121.56     39.08                26.0       1377.0   
20613  20613    -121.55     39.09                31.0       1728.0   
20614  20614    -121.54     39.08                26.0       2276.0   
20616  20616    -121.53     39.08                15.0       1810.0   
20617  20617    -121.53     39.06                20.0        561.0   
20618  20618    -121.55     39.06                25.0       1332.0   
20620  20620    -121.48     39.05                40.0        198.0   
20621  20621    -121.47     39.01                37.0       1244.0   
20622  20622    -121.44     39.00                20.0        755.0   
20623  20623    -121.37     39.03                32.0       1158.0   
20624  20624    -121.41     39.04                16.0       1698.0   
20626  20626    -121.43     39.18                36.0       1124.0   
20627  20627    -121.32     39.13                 5.0        358.0   
20628  20628    -121.48     39.10                19.0       2043.0   
20629  20629    -121.39     39.12                28.0      10035.0   
20630  20630    -121.32     39.29                11.0       2640.0   
20631  20631    -121.40     39.33                15.0       2655.0   
20634  20634    -

In [47]:
from sklearn.model_selection import StratifiedKFold

X = np.ones(10)
y = [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
skf = StratifiedKFold(n_splits=4)
for train, test in skf.split(X, y):
    print("%s %s" % (train, test))

[1 2 3 6 7 8 9] [0 4 5]
[0 2 3 4 5 8 9] [1 6 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 2 4 5 6 7 8] [3 9]


In [48]:
    >>> import numpy as np
    >>> from sklearn.model_selection import train_test_split
    >>> from sklearn import datasets
    >>> from sklearn import svm
    >>> from sklearn.model_selection import cross_val_score

    >>> iris = datasets.load_iris()
    >>> clf = svm.SVC(kernel='linear', C=1)
    >>> scores = cross_val_score(clf, iris.data, iris.target, cv=5)
    >>> scores        

D:\python\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])