# 第一章

#### 简单生成一个行向量

In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

#### 行向量的转置 (无效做法)
    
__注意：__ `.transpose` 方法对一维数组是无效的。

In [8]:
a.transpose()

array([1, 2, 3, 4])

#### 行向量的转置

In [10]:
a_t = a[:,np.newaxis]
a_t

array([[1],
       [2],
       [3],
       [4]])

#### 直接生成一个列向量 (二维数组)

可以把列向量看成是一个 `n * 1` 的矩阵

In [12]:
A = np.array([[1,2,3,4]])
A.T

array([[1],
       [2],
       [3],
       [4]])

#### 向量的内积

可以看成是 u 在 v 上的投影长度乘以 v 的模长，如果 v 为单位向量，则 u 和 v 的内积即为 u 在 v 上的模长。

In [39]:
u = np.array([3,5,2])
v = np.array([1,4,7])
np.dot(u,v)

37

顺序不改变结果

In [50]:
u = np.array([3,5,2])
v = np.array([1,4,7])
np.dot(v,u)

37

__注意__ ：当使用矩阵进行 `.dot` 计算时要满足矩阵乘法的条件。 

可以发现： `a · b = abT`  ，即：`a和b内积` 的结果相当于 `a和b的转置相乘` 的结果

In [48]:
u = np.array([[3,5,2]])
v = np.array([[1,4,7]]).T
np.dot(u,v)

array([[37]])

__注意__： 通常情况下，线性代数下的向量是列向量 即 `n * 1` 的向量。

所以对于两个向量都是 `列向量` 之间的点积为：`a · b = aTb` 

In [57]:
u_t = np.array([[3,5,2]]).T
v_t = np.array([[1,4,7]]).T
np.dot(u_t.T,v_t)

array([[37]])

#### 向量的外积

二维平面中，向量的外积表示两个向量张成的平行四边形的 "面积"

In [15]:
u = np.array([3,5])
v = np.array([1,4])
np.cross(u,v)

array(7)

三维空间中，u 和 v 向量的外积表示两个向量张成平面的法向量

In [16]:
u = np.array([3,3,9])
v = np.array([1,4,12])
np.cross(u,v)

array([  0, -27,   9])

#### 生成一个零矩阵

In [18]:
A = np.zeros([5,3])
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

####  生成一个对角矩阵

In [21]:
A = np.diag([1,2,3,4,5])
A

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

####  生成一个单位矩阵

In [20]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 矩阵和矩阵相乘

也是使用 `.dot` 方法

In [23]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3,4],[5,6,7,8]])
np.dot(A,B)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68],
       [47, 62, 77, 92]])

# 第二章

# 第三章